name: lint
on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  
jobs:
  
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.17'
          cache: false
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.29
  
  golint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - 
        name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go
          
      - 
        name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  gotests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: tests
        run: cd fmc && go test -v
  gendir:
    runs-on: ubuntu-latest
    steps:
      - name: Template Format Check
        uses: jordanbean-msft/github-action-wth-template-check@v0.4.0
        with:
          path: ${{ github.workspace }}
          shouldScanSubdirectories: true
          
  gendocs:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - 
        name: gendocs
        run: go get github.com/hashicorp/terraform-plugin-docs@latest
        
      - 
        name: gendocst
        run: go mod vendor && go generate ./... 

          
          
          
  list:
    name: Path lister
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: actions/checkout@v1

      - name: Fetch action
        id: pl
        uses: Rishabh510/Path-lister-action@master
        with:
          path: "/"
          type: ".tf"

      - name: Output results
        run: |
          echo "Found ${{ steps.pl.outputs.path_count }} file(s) with this extension:"
          for i in ${{ steps.pl.outputs.paths }}; do
          echo $i
          done
  test:
    runs-on: ubuntu-latest
    name: Test Collect Directory Names action
    steps:
      - name: Get directory names
        id: get-directory-names
        uses:  actions/checkout@v2
        with:
          file-glob: '**/*.tf'
          search-directory: '/'
          unique: "true"
  
      - name: Use Directory Names
        run: echo "Directory Names are ${{ steps.get-directory-names.outputs.directory-names}}"
